paths:
    tests: .tests/php
    output: .codeception/_output
    data: .codeception/_data
    support: .codeception/_support
    envs: .codeception/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
params:
    - env
    - .codeception/_config/params.php
settings:
    backup_globals: false
    colors: true
coverage:
    enabled: true
    low_limit: 20
    high_limit: 60
    show_only_summary: true
    include:
        - ./backend/*
        - ./bbp/*
        - ./bp/*
        - ./cf7/*
        - ./common/*
        - ./default/*
        - ./deploy/*
        - ./jetpack/*
        - ./mailchimp/*
        - ./nf/*.php
        - ./subscriber/*
        - ./wc/*
        - ./wc_wl/*
        - ./wpforms/*
        - ./wpforo/*
        - ./hcaptcha.php
