# Travis CI (MIT License) configuration file
# @link https://travis-ci.org/

# Use new container based environment
sudo: false

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  fast_finish: true

  include:
    - php: '5.6'
      env:
        - DEV="--no-dev"
    - php: '7.0'
      env:
        - DEV="--no-dev"
    - php: '7.1'
      env:
        - DEV="--no-dev"
    - php: '7.2'
      env:
        - DEV="--no-dev"
    - php: '7.3'
      env:
        - DEV="--no-dev"
    - php: '7.4'
      env:
        - SNIFF=1
    - php: 'nightly'
        - DEV="--no-dev"

  allow_failures:
    - php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

before_script:
  - phpenv rehash
  - composer install $DEV

script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run PHPCS.
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs --colors; fi
