name: Plugin readme/assets update
on:
  push:
    branches:
      - trunk
permissions:
  actions: read
  contents: read
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: WordPress.org plugin asset/readme update
        uses: hCaptcha/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7 # v2.2.0
        env:
          SLUG: hcaptcha-for-forms-and-more
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          IGNORE_OTHER_FILES: true
