name: Deploy to WordPress.org
on:
  release:
    types: [published]
permissions:
  actions: read
  contents: write
jobs:
  tag:
    name: New release

    runs-on: ubuntu-latest

    # Security: 1. Check if user is authorized.
    if: contains(fromJson('["kagg-design", "e271828-"]'), github.actor)

    env:
      SLUG: "hcaptcha-for-forms-and-more"

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dependencies with caching
        uses: hCaptcha/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          composer-options: "--no-dev --optimize-autoloader --classmap-authoritative"

      - name: Install packages
        run: |
          corepack enable
          yarn set version stable
          yarn
          yarn prod

      - name: WordPress Plugin Deploy
        id: deploy
        uses: hCaptcha/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2
        with:
          generate-zip: true
        env:
          SLUG: ${{ env.SLUG }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      - name: Upload release asset
        uses: hCaptcha/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda #v3.0.0
        with:
          files: ${{github.workspace}}/${{ env.SLUG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
